{
  description = "Browse, search, and edit Shortcut stories and epics from Neovim";

  inputs.nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";

  outputs =
    { self, nixpkgs }:
    let
      inherit (nixpkgs) lib;

      # nixpkgs-unstable no longer supports x86_64-darwin (dropped in 26.11).
      systems = [
        "x86_64-linux"
        "aarch64-linux"
        "aarch64-darwin"
      ];
      forAllSystems = f: lib.genAttrs systems (system: f nixpkgs.legacyPackages.${system});

      version = "0.1.0-dev";

      # Only the files that make up the plugin, so edits to tests/CI/flake don't cause rebuilds.
      pluginSrc = lib.fileset.toSource {
        root = ./.;
        fileset = lib.fileset.unions [
          ./lua
          ./plugin
          (lib.fileset.maybeMissing ./doc)
          ./LICENSE
          ./README.md
        ];
      };

      # The plugin plus everything needed to run the test suite.
      testSrc = lib.fileset.toSource {
        root = ./.;
        fileset = lib.fileset.unions [
          ./lua
          ./plugin
          ./tests
          ./Makefile
          ./.stylua.toml
        ];
      };

      mkPlugin =
        pkgs:
        pkgs.vimUtils.buildVimPlugin {
          pname = "shortcut.nvim";
          inherit version;
          src = pluginSrc;
          # Added to PATH by Neovim wrappers (`autowrapRuntimeDeps`).
          runtimeDeps = [
            pkgs.curl
            pkgs.git
          ];
          # buildVimPlugin requires every module as a check. Modules that need optional
          # dependencies (e.g. snacks.nvim) should be covered via `checkInputs` or skipped
          # with `nvimSkipModules`.
          meta = {
            description = "Browse, search, and edit Shortcut stories and epics from Neovim";
            homepage = "https://github.com/calebstewart/shortcut.nvim";
            license = lib.licenses.mit;
            platforms = lib.platforms.all;
          };
        };

      # Minimal config for the `nix run` instances. Deliberately not the user's config.
      devInitLua = ''
        -- Generated by shortcut.nvim's flake for `nix run`; not your personal config.
        vim.g.mapleader = ' '
        vim.o.number = true
        vim.o.signcolumn = 'yes'
        vim.o.termguicolors = true

        vim.api.nvim_create_autocmd('FileType', {
          pattern = 'markdown',
          callback = function(ev) pcall(vim.treesitter.start, ev.buf) end,
        })

        require('snacks').setup({
          picker = { enabled = true },
          notifier = { enabled = true },
          input = { enabled = true },
        })
        require('shortcut').setup({})
      '';

      # Neovim with snacks.nvim, the yaml grammar (for story headers) and `extraPlugins`,
      # isolated from the user's own config/state/cache via NVIM_APPNAME.
      mkDevNeovim =
        pkgs: extraPlugins:
        pkgs.wrapNeovimUnstable pkgs.neovim-unwrapped {
          plugins = extraPlugins ++ [
            pkgs.vimPlugins.snacks-nvim
            (pkgs.vimPlugins.nvim-treesitter.withPlugins (p: [ p.yaml ]))
          ];
          luaRcContent = devInitLua;
          withRuby = false;
          withPython3 = false;
          withNodeJs = false;
          wrapperArgs = [
            "--set-default"
            "NVIM_APPNAME"
            "shortcut-nvim-dev"
            "--prefix"
            "PATH"
            ":"
            (lib.makeBinPath [
              pkgs.curl
              pkgs.git
            ])
          ];
        };

      # Like the default app, but loads the plugin from the working tree instead of the store.
      mkDevLauncher =
        pkgs:
        let
          nvim = mkDevNeovim pkgs [ ];
        in
        pkgs.writeShellApplication {
          name = "shortcut-nvim-dev";
          text = ''
            dir="''${SHORTCUT_NVIM_DIR:-$PWD}"
            if [[ ! -f "$dir/lua/shortcut/init.lua" ]]; then
              echo "shortcut-nvim-dev: '$dir' is not a shortcut.nvim checkout." >&2
              echo "Run from the repository root or set SHORTCUT_NVIM_DIR." >&2
              exit 1
            fi
            SHORTCUT_NVIM_DIR="$(cd "$dir" && pwd)"
            export SHORTCUT_NVIM_DIR
            exec ${nvim}/bin/nvim --cmd 'lua vim.opt.runtimepath:prepend(vim.env.SHORTCUT_NVIM_DIR)' "$@"
          '';
        };

      systemOf = pkgs: pkgs.stdenv.hostPlatform.system;
    in
    {
      overlays.default = final: prev: {
        vimPlugins = prev.vimPlugins.extend (_: _: { shortcut-nvim = mkPlugin final; });
      };

      packages = forAllSystems (pkgs: rec {
        shortcut-nvim = mkPlugin pkgs;
        default = shortcut-nvim;
      });

      apps = forAllSystems (pkgs: {
        default = {
          type = "app";
          program = "${mkDevNeovim pkgs [ self.packages.${systemOf pkgs}.default ]}/bin/nvim";
          meta.description = "Neovim with the packaged shortcut.nvim (isolated config)";
        };
        dev = {
          type = "app";
          program = lib.getExe (mkDevLauncher pkgs);
          meta.description = "Neovim with shortcut.nvim loaded from the working tree";
        };
      });

      devShells = forAllSystems (pkgs: {
        default = pkgs.mkShellNoCC {
          packages = [
            pkgs.neovim-unwrapped
            pkgs.stylua
            pkgs.lua-language-server
            pkgs.curl
            pkgs.git
            pkgs.gnumake
            pkgs.nixfmt
          ];
          # Used by the Makefile/tests instead of cloning mini.nvim and snacks.nvim into deps/.
          MINI_NVIM = "${pkgs.vimPlugins.mini-nvim}";
          SNACKS_NVIM = "${pkgs.vimPlugins.snacks-nvim}";
        };
      });

      checks = forAllSystems (pkgs: {
        plugin = self.packages.${systemOf pkgs}.default;

        tests =
          pkgs.runCommand "shortcut-nvim-tests"
            {
              nativeBuildInputs = [
                pkgs.neovim-unwrapped
                pkgs.gnumake
              ];
              MINI_NVIM = "${pkgs.vimPlugins.mini-nvim}";
              SNACKS_NVIM = "${pkgs.vimPlugins.snacks-nvim}";
            }
            ''
              cp -r ${testSrc} src
              chmod -R u+w src
              cd src
              export HOME="$TMPDIR"
              make test
              touch $out
            '';

        format = pkgs.runCommand "shortcut-nvim-format" { nativeBuildInputs = [ pkgs.stylua ]; } ''
          cd ${testSrc}
          stylua --check .
          touch $out
        '';
      });

      formatter = forAllSystems (pkgs: pkgs.nixfmt);
    };
}
